/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimationRouteImport } from './routes/animation'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CompetidoresRouteImport } from './routes/competidores'
import { Route as ConexionesRouteImport } from './routes/conexiones'
import { Route as CrearRouteImport } from './routes/crear'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as ImagenesRouteImport } from './routes/imagenes'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiPublicHooksCronTickRouteImport } from './routes/api/public/hooks/cron-tick'
import { Route as ApiPublicHooksUnipileRouteImport } from './routes/api/public/hooks/unipile'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationRoute = AnimationRouteImport.update({
  id: '/animation',
  path: '/animation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetidoresRoute = CompetidoresRouteImport.update({
  id: '/competidores',
  path: '/competidores',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexionesRoute = ConexionesRouteImport.update({
  id: '/conexiones',
  path: '/conexiones',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearRoute = CrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagenesRoute = ImagenesRouteImport.update({
  id: '/imagenes',
  path: '/imagenes',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCronTickRoute = ApiPublicHooksCronTickRouteImport.update({
  id: '/api/public/hooks/cron-tick',
  path: '/api/public/hooks/cron-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUnipileRoute = ApiPublicHooksUnipileRouteImport.update({
  id: '/api/public/hooks/unipile',
  path: '/api/public/hooks/unipile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animation': typeof AnimationRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/calendario': typeof CalendarioRoute
  '/chat': typeof ChatRoute
  '/competidores': typeof CompetidoresRoute
  '/conexiones': typeof ConexionesRoute
  '/crear': typeof CrearRoute
  '/guia': typeof GuiaRoute
  '/imagenes': typeof ImagenesRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/logs': typeof LogsRoute
  '/marca': typeof MarcaRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/public/hooks/cron-tick': typeof ApiPublicHooksCronTickRoute
  '/api/public/hooks/unipile': typeof ApiPublicHooksUnipileRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animation': typeof AnimationRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/calendario': typeof CalendarioRoute
  '/chat': typeof ChatRoute
  '/competidores': typeof CompetidoresRoute
  '/conexiones': typeof ConexionesRoute
  '/crear': typeof CrearRoute
  '/guia': typeof GuiaRoute
  '/imagenes': typeof ImagenesRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/logs': typeof LogsRoute
  '/marca': typeof MarcaRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/public/hooks/cron-tick': typeof ApiPublicHooksCronTickRoute
  '/api/public/hooks/unipile': typeof ApiPublicHooksUnipileRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animation': typeof AnimationRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/calendario': typeof CalendarioRoute
  '/chat': typeof ChatRoute
  '/competidores': typeof CompetidoresRoute
  '/conexiones': typeof ConexionesRoute
  '/crear': typeof CrearRoute
  '/guia': typeof GuiaRoute
  '/imagenes': typeof ImagenesRoute
  '/inbox': typeof InboxRoute
  '/library': typeof LibraryRoute
  '/logs': typeof LogsRoute
  '/marca': typeof MarcaRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/public/hooks/cron-tick': typeof ApiPublicHooksCronTickRoute
  '/api/public/hooks/unipile': typeof ApiPublicHooksUnipileRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animation'
    | '/approvals'
    | '/auth'
    | '/automations'
    | '/calendario'
    | '/chat'
    | '/competidores'
    | '/conexiones'
    | '/crear'
    | '/guia'
    | '/imagenes'
    | '/inbox'
    | '/library'
    | '/logs'
    | '/marca'
    | '/onboarding'
    | '/reports'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/public/hooks/cron-tick'
    | '/api/public/hooks/unipile'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animation'
    | '/approvals'
    | '/auth'
    | '/automations'
    | '/calendario'
    | '/chat'
    | '/competidores'
    | '/conexiones'
    | '/crear'
    | '/guia'
    | '/imagenes'
    | '/inbox'
    | '/library'
    | '/logs'
    | '/marca'
    | '/onboarding'
    | '/reports'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/public/hooks/cron-tick'
    | '/api/public/hooks/unipile'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/animation'
    | '/approvals'
    | '/auth'
    | '/automations'
    | '/calendario'
    | '/chat'
    | '/competidores'
    | '/conexiones'
    | '/crear'
    | '/guia'
    | '/imagenes'
    | '/inbox'
    | '/library'
    | '/logs'
    | '/marca'
    | '/onboarding'
    | '/reports'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/public/hooks/cron-tick'
    | '/api/public/hooks/unipile'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimationRoute: typeof AnimationRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuthRoute: typeof AuthRoute
  AutomationsRoute: typeof AutomationsRoute
  CalendarioRoute: typeof CalendarioRoute
  ChatRoute: typeof ChatRoute
  CompetidoresRoute: typeof CompetidoresRoute
  ConexionesRoute: typeof ConexionesRoute
  CrearRoute: typeof CrearRoute
  GuiaRoute: typeof GuiaRoute
  ImagenesRoute: typeof ImagenesRoute
  InboxRoute: typeof InboxRoute
  LibraryRoute: typeof LibraryRoute
  LogsRoute: typeof LogsRoute
  MarcaRoute: typeof MarcaRoute
  OnboardingRoute: typeof OnboardingRoute
  ReportsRoute: typeof ReportsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiPublicHooksCronTickRoute: typeof ApiPublicHooksCronTickRoute
  ApiPublicHooksUnipileRoute: typeof ApiPublicHooksUnipileRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animation': {
      id: '/animation'
      path: '/animation'
      fullPath: '/animation'
      preLoaderRoute: typeof AnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competidores': {
      id: '/competidores'
      path: '/competidores'
      fullPath: '/competidores'
      preLoaderRoute: typeof CompetidoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexiones': {
      id: '/conexiones'
      path: '/conexiones'
      fullPath: '/conexiones'
      preLoaderRoute: typeof ConexionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear': {
      id: '/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof CrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagenes': {
      id: '/imagenes'
      path: '/imagenes'
      fullPath: '/imagenes'
      preLoaderRoute: typeof ImagenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cron-tick': {
      id: '/api/public/hooks/cron-tick'
      path: '/api/public/hooks/cron-tick'
      fullPath: '/api/public/hooks/cron-tick'
      preLoaderRoute: typeof ApiPublicHooksCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/unipile': {
      id: '/api/public/hooks/unipile'
      path: '/api/public/hooks/unipile'
      fullPath: '/api/public/hooks/unipile'
      preLoaderRoute: typeof ApiPublicHooksUnipileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimationRoute: AnimationRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuthRoute: AuthRoute,
  AutomationsRoute: AutomationsRoute,
  CalendarioRoute: CalendarioRoute,
  ChatRoute: ChatRoute,
  CompetidoresRoute: CompetidoresRoute,
  ConexionesRoute: ConexionesRoute,
  CrearRoute: CrearRoute,
  GuiaRoute: GuiaRoute,
  ImagenesRoute: ImagenesRoute,
  InboxRoute: InboxRoute,
  LibraryRoute: LibraryRoute,
  LogsRoute: LogsRoute,
  MarcaRoute: MarcaRoute,
  OnboardingRoute: OnboardingRoute,
  ReportsRoute: ReportsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiPublicHooksCronTickRoute: ApiPublicHooksCronTickRoute,
  ApiPublicHooksUnipileRoute: ApiPublicHooksUnipileRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
